Update main-workflow.yml

diff --git a/.github/workflows/main-workflow.yml b/.github/workflows/main-workflow.yml
--- a/.github/workflows/main-workflow.yml
+++ b/.github/workflows/main-workflow.yml
@@ -28,19 +28,16 @@ jobs:
         run: |
           coverage run --branch typewise_alert.test.py
           coverage html
-          coverage report
           COVERAGE=$(coverage report | grep TOTAL | awk '{print $NF}')
-              if (( $(echo "$COVERAGE < 100" | bc -l) )); then
-                echo "Coverage is less than 90%. Failing the build..."
-                exit 1
-              else
-                echo "Coverage is greater than or equal to 90%."
-              fi
-       
+          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
+            echo "Coverage is less than 90%. Failing the build..."
+            exit 1
+          else
+            echo "Coverage is greater than or equal to 90%."
+          fi
       - name: Upload coverage
         uses: actions/upload-artifact@v2
         with:
           name: coverage
           path: ./htmlcov
           retention-days: 21
-                     
