Update main-workflow.yml

diff --git a/.github/workflows/main-workflow.yml b/.github/workflows/main-workflow.yml
--- a/.github/workflows/main-workflow.yml
+++ b/.github/workflows/main-workflow.yml
@@ -30,10 +30,12 @@ jobs:
           coverage html
           coverage report
           COVERAGE=$(coverage report | grep TOTAL | awk '{print $NF}')
-          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
-            echo "Coverage is less than 90%. Failing the build..."
-            exit 1
-          fi
+              if (( $(echo "$COVERAGE < 100" | bc -l) )); then
+                echo "Coverage is less than 90%. Failing the build..."
+                exit 1
+              else
+                echo "Coverage is greater than or equal to 90%."
+              fi
        
       - name: Upload coverage
         uses: actions/upload-artifact@v2
