Update main-workflow.yml

diff --git a/.github/workflows/main-workflow.yml b/.github/workflows/main-workflow.yml
--- a/.github/workflows/main-workflow.yml
+++ b/.github/workflows/main-workflow.yml
@@ -30,12 +30,14 @@ jobs:
           coverage html
           coverage report
           COVERAGE=$(coverage report | awk 'END{print $NF}')
-          if python -c "import math; print(math.floor(int(${COVERAGE})) < 100%)"; then
-              echo "Coverage is less than 100%. Failing the build..."
-              exit 1
+          COVERAGE_INT=$(printf "%.0f" $COVERAGE)
+          if [ "$COVERAGE_INT" -lt 100 ]; then
+            echo "Coverage is less than 100%. Failing the build..."
+            exit 1
           else
-              echo "Coverage is greater than or equal to 100%."
+            echo "Coverage is greater than or equal to 100%."
           fi
+
       - name: Upload coverage
         uses: actions/upload-artifact@v2
         with:
