Update main-workflow.yml

diff --git a/.github/workflows/main-workflow.yml b/.github/workflows/main-workflow.yml
--- a/.github/workflows/main-workflow.yml
+++ b/.github/workflows/main-workflow.yml
@@ -29,15 +29,13 @@ jobs:
           coverage run --branch typewise_alert.test.py
           coverage html
           coverage report
-          COVERAGE=$(coverage report | awk 'END{print $NF}')
-          COVERAGE_INT=$(printf -v "%.0f" $COVERAGE)
-          if [ "$COVERAGE_INT" -lt 100 ]; then
-            echo "Coverage is less than 100%. Failing the build..."
-            exit 1
+          COVERAGE=$(coverage report | awk 'END{print $NF}' | sed 's/[^0-9]*//g')
+          if [ "$COVERAGE" -lt 100 ]; then
+              echo "Coverage is less than 100%. Failing the build..."
+              exit 1
           else
-            echo "Coverage is greater than or equal to 100%."
+              echo "Coverage is greater than or equal to 100%."
           fi
-
       - name: Upload coverage
         uses: actions/upload-artifact@v2
         with:
